services:
  web:
    build: .
    container_name: sistema-adocao-web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "*"
    volumes:
      - .:/app
      - media:/app/media
    restart: unless-stopped
volumes:
  media:
    driver: local
